### ISSUE TITLE
Unable to connect on Windows

### ISSUE THREAD

**Issue by gmyers-amfam** [foxpass/foxpass-ipsec-vpn#16]
We're running a Foxpass VPN server in EC2 to allow users to connect into the VPC. Mac Users are able to connect just fine to the VPN server. However, users of Windows (10) are unable to connect. I have more details about the issue including screenshots over [on Server Fault](https://serverfault.com/questions/901720/how-do-i-get-an-l2tp-foxpass-vpn-connection-working-in-windows-10). Is this VPN server compatible with Windows? What extra settings need to be configured to get it working on that platform?

**Comment by aren** [comment]
You're right about the AssumeUDPEncapsulationContextOnSendRule registry entry. The other thing I think you're missing is to enable PAP authentication.

We have these steps outlined for Windows 8, but not Windows 10 yet: https://foxpass.readme.io/docs/foxpass-windows-8-l2tpipsec-setup

I was able to get it working from my Windows 10 test machine, so drop us a line if you run into trouble and we'll walk through it.

**Comment by vkmsa** [comment]
while running the command: packer build foxpass_vpn.json, I am getting below error 

`amazon-ebs: sudo: unable to execute /tmp/foxpass-vpn/scripts/setup.sh: No such file or directory`

But I think all these directories were transferred successfully in previous steps, I can see in my log
```
==> amazon-ebs: Uploading scripts => /tmp/foxpass-vpn
==> amazon-ebs: Uploading templates => /tmp/foxpass-vpn
==> amazon-ebs: Uploading static => /tmp/foxpass-vpn
==> amazon-ebs: Uploading foxpass-radius-agent => /tmp/foxpass-vpn
==> amazon-ebs: Uploading requirements.txt => /tmp/foxpass-vpn/requirements.txt
```

**Comment by ttheune** [comment]
> while running the command: packer build foxpass_vpn.json, I am getting below error
> 
> `amazon-ebs: sudo: unable to execute /tmp/foxpass-vpn/scripts/setup.sh: No such file or directory`
> 
> But I think all these directories were transferred successfully in previous steps, I can see in my log
> 
> ```
> ==> amazon-ebs: Uploading scripts => /tmp/foxpass-vpn
> ==> amazon-ebs: Uploading templates => /tmp/foxpass-vpn
> ==> amazon-ebs: Uploading static => /tmp/foxpass-vpn
> ==> amazon-ebs: Uploading foxpass-radius-agent => /tmp/foxpass-vpn
> ==> amazon-ebs: Uploading requirements.txt => /tmp/foxpass-vpn/requirements.txt
> ```

This is under the wrong issue, and I believe this issue should be closed anyway.  Would it be possible for you (@vkmsa) to open this under a new issue for the project?
